### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by enukepro** [MultiChain/multichain-web-demo#1]
Error: HTTP 0
http://172.31.XX.XX:5767/

**Comment by jaswalabhijeet** [comment]
Check your config.txt and make sure you have all the parameters defined properly i.e. if the web server is in same system place host as 127.0.0.1 else the IP of the server/VM and add rpcallowip=[IP address of your web server] in config.txt.. do you have php curl installed?

**Comment by enukepro** [comment]
Hi Buddy,

Thanks for your reply.

I tried all changes. But facing same issue.
Here are my details.

http://multichain.yiipro.com

config.txt
chain2.name=chain2                  # name to display in the web interface
chain2.rpchost=127.0.0.1              # IP address of MultiChain node
chain2.rpcport=5767                 # see rpc-port from chain parameters
chain2.rpcuser=multichainrpc          # username for RPC from
multichain.conf
chain2.rpcpassword=BzzQn4BZLRTFqb7YFKUaqNagLDdRx3u5o2uHKWKhhZRy

------------------/multichain.conf

rpcallowip=54.148.39.174
rpcuser=multichainrpc
rpcpassword=BzzQn4BZLRTFqb7YFKUaqNagLDdRx3u5o2uHKWKhhZRy

could you please have a look once?

 Thanks & Regards
 Hari Kishore
 Email: hari.kishore@enukesoftware.com
 Skype: hari.enuke
Mobile: +91 9910527506

**Comment by jaswalabhijeet** [comment]
is your web server in the same system where multichain node is running? if so then you need to add the rpcallowip parameter.

**Comment by enukepro** [comment]
Hi,

Yes, Same server is using and have already added following parameters.

rpcallowip=54.148.39.174
rpcuser=multichainrpc
rpcpassword=BzzQn4BZLRTFqb7YFKUaqNagLDdRx3u5o2uHKWKhhZRy


 Thanks & Regards
 Hari Kishore
 Email: hari.kishore@enukesoftware.com
 Skype: hari.enuke
Mobile: +91 9910527506

**Comment by jaswalabhijeet** [comment]
My bad.. if the web server is in same system as of node then you don't need to add rpallowip

**Comment by enukepro** [comment]
Hi,

Thanks for you assistance.

Now its working fine. Let me check all features.
If i find any issue, will email you.



 Thanks & Regards
 Hari Kishore
 Email: hari.kishore@enukesoftware.com
 Skype: hari.enuke
Mobile: +91 9910527506

**Comment by jaswalabhijeet** [comment]
Happy to help..I dont work in multichain but sumeone who has used it.. please post your issues in github.
