### ISSUE TITLE
API error 702 on web demo

### ISSUE THREAD

**Issue by xavalex** [MultiChain/multichain-web-demo#13]
Hi, 

I am getting the main web demo page but see some fields not filling up and a "Error 702, API not supported for this protocol version" I presume a version conflict between the server and the pages?

**Comment by gidgreen** [comment]
You're probably running a chain started with an old version of MultiChain. In this case some of the web demo functionality won't work. You can start a new chain in a recent version of MultiChain, if that's an option.

**Comment by xavalex** [comment]
I just installed multichain again, compiling from Github, and still have the same issue alas. I am wondering whether the issue might not be in the web-demo version. Shall check that.

**Comment by gidgreen** [comment]
Please check the protocol-version of your chain.

**Comment by xavalex** [comment]
Here it is : protocolversion" : 10005.

**Comment by gidgreen** [comment]
That's your problem. A bunch of functionality (e.g. streams) was introduced in later protocols. If you want to access this functionality, you should start a new chain, with at least protocol 10008. (From that protocol on, there's also an upgrade path to later protocols.)

**Comment by xavalex** [comment]
Thanks. Sorted out. Cheers.
