### ISSUE TITLE
Error for web demo

### ISSUE THREAD

**Issue by maplerichie** [MultiChain/multichain-web-demo#2]
[root@local multichain]# cat ~/.multichain/chain1/multichain.conf
rpcuser=multichainrpc
rpcpassword=9vyymfxCt51WqojUnWF8y9PgkfVMUVaXEAu7s2861voQ

[root@local multichain]# grep rpc-port ~/.multichain/chain1/params.dat
default-rpc-port = 4384                 # Default TCP/IP port for incoming JSON-RPC API requests.

[root@local multichain]# cat config.txt
default.name=Default                   # name to display in the web interface
default.rpchost=127.0.0.1              # IP address of MultiChain node
default.rpcport=4384                  # see rpc-port from chain parameters
default.rpcuser=multichainrpc          # username for RPC from multichain.conf
default.rpcpassword=9vyymfxCt51WqojUnWF8y9PgkfVMUVaXEAu7s2861voQ

[root@local multichain]# ps aux | grep multichain
root      8633  0.3  0.4 954304 34916 ?        SLsl 18:24   0:02 multichaind chain1 -daemon

Is my configuration error?

**Comment by gidgreen** [comment]
Please ask these sorts of questions on the MultiChain Q&A:

http://www.multichain.com/qa/
