### ISSUE TITLE
error: -32601 Method not found

### ISSUE THREAD

**Issue by rknidzam** [MultiChain/multichain-web-demo#3]
Hello, I am new in multi chain. I just installed this framework with following all the guides. But somehow I have an error with code -32601 which comes with desription of "Method not found". Other than that, there is also undefined index: address in page-permission.php on line 34. Can you please give some idea if there are any?

**Comment by gidgreen** [comment]
Please ask these sorts of questions on the MultiChain Q&A:

http://www.multichain.com/qa/
