### ISSUE TITLE
"Error: HTTP 0" while accessing chaincode

### ISSUE THREAD

**Issue by bharathapj17** [MultiChain/multichain-web-demo#4]
Hi,
I created and started a multichain named as blockchain. On start it shows following info:

C:\multichain>multichaind blockchain -daemon

MultiChain Core Daemon build 1.0 beta 1 protocol 10008

Other nodes can connect to this node using:
multichaind blockchain@192.168.56.1:2893

This host has multiple IP addresses, so from some networks:

multichaind blockchain@192.168.1.121:2893

Node started

My multichain.conf file has following params:

rpcuser=multichainrpc
rpcpassword=7uCEV2CgVp27NpQ2AdqteyDQLZMks8VJPmF5WuqYSrGS
rpcport=2893
rpcallowip=192.168.1.121
rpcallowip=127.0.0.1
rpcallowip=10.0.2.15/255.0.0.0
rpcallowip=192.168.56.1/255.255.255.0
rpcallowip=192.168.1.0/255.255.255.0

I downloaded the github multichain web demo code and moved it to xampp apache server. I added the configuration file, i.e. config.txt as below:
blockchain.name=blockchain                   
blockchain.rpchost=192.168.1.121    
blockchain.rpcport=2893                  
blockchain.rpcuser=multichainrpc          blockchain.rpcpassword=7uCEV2CgVp27NpQ2AdqteyDQLZMks8VJPmF5WuqYSrGS         

Now when I access localhost/multichain-demo-master and click on blockchain, It throws:
Error: HTTP 0          
http://192.168.1.121:2893/

If I change the rcphost to 127.0.0.1, error still remains.

Please help me with the configurations to make it run.
![error1](https://cloud.githubusercontent.com/assets/28055563/26615603/abe8a9d0-45e5-11e7-8df8-74fee8fb8c47.PNG)

**Comment by gidgreen** [comment]
Please ask these sorts of questions on the Q&A:

http://www.multichain.com/qa/
