### ISSUE TITLE
Error accepting offer

### ISSUE THREAD

**Issue by NarubyRiverlione** [MultiChain/multichain-web-demo#5]
When I complete an offer I get: "error -1 value is type array, expected real"
[screenshot](https://www.dropbox.com/s/duxexxz7yzqy030/Multichain%20error.png?dl=0)

Apache error log: 
`[Sun Jun 04 16:22:37.766605 2017] [:error] [pid 44703] [client 127.0.0.1:62544] PHP Notice:  Undefined index: completeoffer in /Users/xxxx/Sites/multichain/page-accept.php on line 21, referer: http://multichain.local/?chain=default&page=accept`

**Comment by gidgreen** [comment]
Thanks. Can you please uncomment the two lines containing `<PRE>` in the file `functions.php`. This will display the full content of every API request and response in the web page. Then paste them here so we can see which request was actually generating this error.

**Comment by NarubyRiverlione** [comment]
`{"id":1496661335,"method":"decoderawexchange","params":["0100000001131117f3db127ca352b881d523cc4369ee368cbc7cd40d3e38aa2831d72ffdda000000006b483045022100ae04064673088200d29c578605c388b17d0955f4f8048f8202fa2fb5b5c52c0602201fcd707504326c9675be1e815e6a0b88b24f02cbbe46b86d9945a7f1a79fa584832102986b4a5962071d09201b0379fe8c1be48724a79aa585a1469f66ad22c7498b96ffffffff0100000000000000003776a914a4ba64121c23a8e05c38ebdb504512a383ae0b7888ac1c73706b71b2fb2f844ad0aa32cbc7d0205a5bb69101000000000000007500000000"]}

{"result":{"offer":{"amount":0.00000000,"assets":[{"name":"Hours","assetref":"30-265-46737","qty":1.10000000}]},"ask":{"amount":0.00000000,"assets":[]},"requiredfee":0.00000000,"candisable":false,"cancomplete":true,"complete":false},"error":null,"id":1496661335}

{"id":1496661335,"method":"preparelockunspentfrom","params":["15m54h8NSts6nznzaoGdqCYVM82qz2dp3dH2nj",[]]}

{"result":null,"error":{"code":-1,"message":"value is type array, expected real"},"id":1496661335}`

**Comment by gidgreen** [comment]
Thanks. The problem was occurring because you didn't ask for anything in exchange for these `Hours` when making the offer, which is an unusual situation. In any event, we've pushed a fix so that the Web Demo can now work in this case.
