### ISSUE TITLE
Connect more than onw node

### ISSUE THREAD

**Issue by Hefziben** [MultiChain/multichain-web-demo#7]
hello, I wonder if this is possible to connect more than one Node to the web demo. the node section says "Connected Nodes" which initially is one. I Mean
to have 2 nodes showing connected. ex:

My Node
(first) Name: test3
...
(2nd) Name: Test2

**Comment by gidgreen** [comment]
You can certainly have multiple nodes in your blockchain, but this is nothing to do with the Web Demo itself. You can then configure the Web Demo to connect to multiple nodes by setting up multiple configurations in the `config.txt` file, each one with the appropriate node IP address and API credentiails.
